### ISSUE TITLE
How to set the DEP_PATH environment variable?

### ISSUE THREAD

**Issue by cuteJaven** [aufdenpunkt/python-safety-check#1]
Here is my requirement.txt 's path
![image](https://user-images.githubusercontent.com/32606645/109919427-96924e80-7cf3-11eb-9b9c-4f50eb0b5f0a.png)

and here is my yml file's path
![image](https://user-images.githubusercontent.com/32606645/109919544-c3defc80-7cf3-11eb-8286-c40df51a275e.png)

I have tried denoting it with "../../requirement.txt" but it seems does not work. Could you please tell me how to denote the path in the env:DEP_PATH:? 
Thanks!

**Comment by ChihweiLHBird** [comment]
Try `./requirements.txt`. It would be the relevant path from the root of the repository.

**Comment by aufdenpunkt** [comment]
Sorry, I missed the notification. Did you solve this issue? @cuteJaven

**Comment by cuteJaven** [comment]
> Try `./requirements.txt`. It would be the relevant path from the root of the repository.

Thank you, it worked.

**Comment by aufdenpunkt** [comment]
Nice to hear!
